version: "3"
services:
  hellodocker-registry:
    container_name: hellodocker-registry
    image: registry:2.6
    ports:
      - 5000:5000
    volumes:
      - "./registry-data:/var/lib/registry"

  hellodocker-manager:
    container_name: hellodocker-manager
    image: docker:18.05.0-ce-dind
    privileged: true
    tty: true
    ports:
      - 8000:80
      - 9000:9000
    depends_on:
      - hellodocker-registry
    expose:
      - 3375
    command: "--insecure-registry hellodocker-registry:5000"
    volumes:
      - "./stack:/stack"

  hellodocker-worker01:
    container_name: hellodocker-worker01
    image: docker:18.05.0-ce-dind
    privileged: true
    tty: true
    depends_on:
      - hellodocker-manager
      - hellodocker-registry
    expose:
      - 7946
      - 7946/udp
      - 4789/udp
    command: "--insecure-registry hellodocker-registry:5000"

  hellodocker-worker02:
    container_name: hellodocker-worker02
    image: docker:18.05.0-ce-dind
    privileged: true
    tty: true
    depends_on:
      - hellodocker-manager
      - hellodocker-registry
    expose:
      - 7946
      - 7946/udp
      - 4789/udp
    command: "--insecure-registry hellodocker-registry:5000"

  hellodocker-worker03:
    container_name: hellodocker-worker03
    image: docker:18.05.0-ce-dind
    privileged: true
    tty: true
    depends_on:
      - hellodocker-manager
      - hellodocker-registry
    expose:
      - 7946
      - 7946/udp
      - 4789/udp
    command: "--insecure-registry hellodocker-registry:5000"