version: "3"
services:
  master:
    container_name: jenkins-master
    image: jenkins/jenkins
    ports:
      - 8080:8080
    volumes:
      - ../jenkins-master-node/jenkins_home:/var/jenkins_home
    links:
      - slave01

  slave01:
    container_name: jenkins-slave01
    image: jenkins/ssh-slave
    environment:
      - JENKINS_SLAVE_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDFWQu8JE75outuz1JqrWTdKwGjub0G9JGu6FeXo4HJ20aNAo/BbykYl9RwwChs98PiQoEEU7hJZFFO2NP9Siz5jJgusMextkJUDhUfGmP8ePlODAnHsN1uQ3F5wOfaPXF4wKO2np9IFDaG7S5uFuf4ZwoqNlnugRQJeF2GwaEQoAnpTfcmjF7EOf1lVd76RcaaINa1EGJJUao2v0b/UvxOZY4Gpkw9J46CXDAPdoFqBJyHNrnwUtVhBeQE2amWKAZZaeobHqiC0hWEBH7r4J5dF20xYgr7PceG5LOrV4tliZNeX3WWq4SiieM3h6oPlUw73PPZubFwYV8xCQJxwEmt