version: "3"

services:
  haproxy:
    image: hellodocker-registry:5000/kickscar/haproxy
    networks:
      - hellodocker-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
    ports:
      - 80:80
      - 1936:1936

networks:
  hellodocker-network:
    external: true